### ISSUE TITLE
Pass parameter from argocd app to sub helm chart

### ISSUE THREAD

**Issue by gyliu513** [cloud-pak-gitops/instana-gitops#43]
@jianh619

**Comment by gyliu513** [comment]
https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#build-environment

```yaml
  spec:
    source:
      helm:
        parameters:
        - name: app
          value: $ARGOCD_APP_NAME
```
